### ISSUE TITLE
Add https support

### ISSUE THREAD

**Issue by andig** [nischelwitzer/smartfritz#1]
The current implementation uses http. https would be appreciated for allowing external access to the "at home" fritz box. It might make sense to switch from http to request or the request-promise module for this purpose.

**Comment by andig** [comment]
I'm doing a full rewrite- the current code is too cumbersome for my purposes: https://github.com/andig/smartfritz

**Comment by andig** [comment]
Full rewrite is done. Any comments please let me know.

**Comment by nischelwitzer** [comment]
hi,

> Regarding smartfritz I am wondering whether or not @nischelwitzer is still maintaining smartfritz.
> Did you consider contributing your code changes back to the original repo?
> im am still here.

we can update it.

regards,
                 nischi
